[package]
name = "load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait="0.1"
pingora = { version = "0.3", features = [ "lb" ] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
