site_name: ...
site_description: ...
site_url: https://...

theme:
  name: material
  custom_dir: docs
  palette:
    - scheme: default
      primary: orange
      accent: deep-orange
      background: "#FFF3E0"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: orange
      accent: deep-orange
      background: "#212121"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

repo_name: ...
repo_url: https://github.com/...
edit_uri: edit/master/docs/

nav:
  - Introduction: 'index.md'

